// filename: auth.controller.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { Request, Response, NextFunction } from 'express';
import * as authService from './auth.service';
import { signToken } from '../../utils/jwt';
import { setAuthCookie, clearAuthCookie } from '../../utils/cookie';
import { toPublicUser } from '../../models/User';
import { ApiError } from '../../utils/ApiError';
import type { SignupInput, LoginInput } from './auth.schema';

export async function signup(
  req: Request<unknown, unknown, SignupInput>,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const user = await authService.signup(req.body);
    const token = signToken({ userId: user._id.toString(), role: user.role });
    setAuthCookie(res, token);
    res.status(201).json({ user: toPublicUser(user) });
  } catch (err) {
    next(err);
  }
}

export async function login(
  req: Request<unknown, unknown, LoginInput>,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const user = await authService.verifyCredentials(req.body);
    const token = signToken({ userId: user._id.toString(), role: user.role });
    setAuthCookie(res, token);
    res.status(200).json({ user: toPublicUser(user) });
  } catch (err) {
    next(err);
  }
}

export function logout(_req: Request, res: Response): void {
  clearAuthCookie(res);
  res.status(200).json({Message : "Logged Out"});
}

export async function me(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    if (!req.user) {
      throw new ApiError(401, 'NOT_AUTHENTICATED', 'Authentication required');
    }
    const user = await authService.getById(req.user.id);
    res.status(200).json({ user: toPublicUser(user) });
  } catch (err) {
    next(err);
  }
}
