// filename: auth.service.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import bcrypt from 'bcrypt';
import { User, type UserDocument } from '../../models/User';
import { ApiError } from '../../utils/ApiError';
import { env } from '../../config/env';
import type { SignupInput, LoginInput } from './auth.schema';

export async function signup(input: SignupInput): Promise<UserDocument> {
  const existing = await User.findOne({ email: input.email }).lean<{ _id: unknown } | null>();
  if (existing) {
    throw new ApiError(409, 'EMAIL_TAKEN', 'An account with this email already exists');
  }
  const passwordHash = await bcrypt.hash(input.password, env.BCRYPT_COST);
  const user = await User.create({
    name: input.name,
    email: input.email,
    passwordHash,
    role: 'participant',
    status: 'active',
  });
  return user;
}

export async function verifyCredentials(input: LoginInput): Promise<UserDocument> {
  const user = await User.findOne({ email: input.email }).select('+passwordHash');
  if (!user) {
    throw new ApiError(401, 'INVALID_CREDENTIALS', 'Invalid email or password');
  }
  if (user.status !== 'active') {
    throw new ApiError(403, 'ACCOUNT_INACTIVE', 'Account is inactive');
  }
  const ok = await bcrypt.compare(input.password, user.passwordHash);
  if (!ok) {
    throw new ApiError(401, 'INVALID_CREDENTIALS', 'Invalid email or password');
  }
  return user;
}

export async function getById(id: string): Promise<UserDocument> {
  const user = await User.findById(id);
  if (!user) {
    throw new ApiError(401, 'SESSION_INVALID', 'Session is no longer valid');
  }
  return user;
}
