// filename: ApiError.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
export type ErrorDetails = Record<string, unknown>;

export interface ApiErrorBody {
  error: {
    code: string;
    message: string;
    details?: ErrorDetails;
  };
}

export class ApiError extends Error {
  public readonly status: number;
  public readonly code: string;
  public readonly details?: ErrorDetails;

  constructor(status: number, code: string, message: string, details?: ErrorDetails) {
    super(message);
    this.status = status;
    this.code = code;
    if (details !== undefined) {
      this.details = details;
    }
  }

  toJSON(): ApiErrorBody {
    return {
      error: {
        code: this.code,
        message: this.message,
        ...(this.details ? { details: this.details } : {}),
      },
    };
  }
}
