// filename: cookie.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { CookieOptions, Response } from 'express';
import { env } from '../config/env';

export const COOKIE_NAME = 'token';
const SEVEN_DAYS_MS = 1000 * 60 * 60 * 24 * 7;

const baseOptions: CookieOptions = {
  httpOnly: true,
  secure: env.NODE_ENV === 'production',
  sameSite: 'strict',
  domain: env.COOKIE_DOMAIN,
  path: '/',
};

export function setAuthCookie(res: Response, token: string): void {
  res.cookie(COOKIE_NAME, token, { ...baseOptions, maxAge: SEVEN_DAYS_MS });
}

export function clearAuthCookie(res: Response): void {
  res.cookie(COOKIE_NAME, '', { ...baseOptions, maxAge: 0 });
}
