// filename: server/src/config/env.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import dotenv from 'dotenv';
import path from 'path';

// Load .env from the server/ root (two levels up from src/config/)
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

// Helper: parse a number env var with a fallback, fail loudly if value is non-numeric
const optionalNumber = (key: string, fallback: number): number => {
  const raw = process.env[key];
  if (raw === undefined || raw === '') return fallback;
  const parsed = Number(raw);
  if (Number.isNaN(parsed)) {
    throw new Error(`Env var ${key} must be a number, got "${raw}"`);
  }
  return parsed;
};

export const env = {
  NODE_ENV: process.env.NODE_ENV || 'development',
  PORT: optionalNumber('PORT', 5000),
  MONGO_URI: process.env.MONGO_URI || 'mongodb://localhost:27017/quiz',
  JWT_SECRET: process.env.JWT_SECRET || 'change_me_in_production',
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '1d',
  COOKIE_SECRET: process.env.COOKIE_SECRET || 'change_me_too',
  CLIENT_URL: process.env.CLIENT_URL || 'http://localhost:3000',
  BCRYPT_COST: optionalNumber('BCRYPT_COST', 10),
  COOKIE_DOMAIN: process.env.COOKIE_DOMAIN || undefined,
} as const;
