// filename: server/src/config/swagger.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import swaggerJsdoc from 'swagger-jsdoc';
import { env } from './env';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Quiz App API',
      version: '1.0.0',
      description: 'REST API documentation for the Quiz application backend.',
      contact: { name: 'Deloitte Final Assignment' },
    },
    servers: [
      { url: `http://localhost:${env.PORT}`, description: 'Local dev server' },
    ],
    components: {
      securitySchemes: {
        cookieAuth: {
          type: 'apiKey',
          in: 'cookie',
          name: 'token',
          description: 'JWT stored in httpOnly cookie',
        },
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
      schemas: {
        User: {
          type: 'object',
          properties: {
            id: { type: 'string', example: '6712a8f3e1b2c3d4e5f67890' },
            name: { type: 'string', example: 'Jane Doe' },
            email: { type: 'string', example: 'jane@example.com' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        AuthResponse: {
          type: 'object',
          properties: {
            user: { $ref: '#/components/schemas/User' },
            token: { type: 'string', example: 'eyJhbGciOiJIUzI1NiIs...' },
          },
        },
        ErrorResponse: {
          type: 'object',
          properties: {
            message: { type: 'string', example: 'Something went wrong' },
            code: { type: 'string', example: 'BAD_REQUEST' },
          },
        },
      },
    },
    tags: [
      { name: 'Auth', description: 'Authentication endpoints' },
      { name: 'Health', description: 'Server health checks' },
    ],
  },
  // Pick up @swagger comments from these files
  apis: ['./src/modules/**/*.routes.ts', './src/app.ts', './src/server.ts'],
};

export const swaggerSpec = swaggerJsdoc(options);
