// filename: auth.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import { z } from 'zod';

export const UserRole = z.enum(['admin', 'instructor', 'participant']);
export type UserRole = z.infer<typeof UserRole>;

export const UserStatus = z.enum(['active', 'inactive']);
export type UserStatus = z.infer<typeof UserStatus>;

export interface AuthUser {
  id: string;
  role: UserRole;
}

// JWT payload schema — used to validate decoded tokens at the trust boundary
export const jwtPayloadSchema = z.object({
  sub: z.string().min(1),
  role: UserRole,
  iat: z.number().optional(),
  exp: z.number().optional(),
});
export type JwtPayload = z.infer<typeof jwtPayloadSchema>;
