// filename: express.d.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { AuthUser } from './auth';

declare global {
  namespace Express {
    interface Request {
      user?: AuthUser;
    }
  }
}
export {};
