// filename: server/src/app.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import express, { Application } from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import swaggerUi from 'swagger-ui-express';
import { swaggerSpec } from './config/swagger';
import { env } from './config/env';
import authRoutes from './modules/auth/routes/auth.routes';
import adminRoutes from './modules/admin/routes/admin.routes';
import instructorRoutes from './modules/instructor/routes/instructor.routes';
import candidateRoutes from './modules/candidate/routes/candidate.routes';
import { Quiz } from './models/Quiz';
import { errorHandler } from './middleware/errorHandler';

export const createApp = (): Application => {
  const app: Application = express();

  app.use(cors({ origin: env.CLIENT_URL, credentials: true }));
  app.use(express.json());
  app.use(cookieParser());

  // Swagger UI — interactive docs
  app.use(
    '/api-docs',
    swaggerUi.serve,
    swaggerUi.setup(swaggerSpec, {
      customSiteTitle: 'Quiz API Docs',
      swaggerOptions: { persistAuthorization: true },
    })
  );

  // Raw JSON spec (useful for Postman import, codegen, etc.)
  app.get('/api-docs.json', (_req, res) => {
    res.setHeader('Content-Type', 'application/json');
    res.send(swaggerSpec);
  });

  /**
   * @swagger
   * /health:
   *   get:
   *     tags: [Health]
   *     summary: Health check
   *     responses:
   *       200:
   *         description: Server is up
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 status: { type: string, example: ok }
   */
  app.get('/health', (_req, res) => res.json({ status: 'ok' }));

  // Convenience: redirect root → docs
  app.get('/', (_req, res) => res.redirect('/api-docs'));

  // Middleware to auto-transition quiz states based on current server time
  app.use(async (_req, _res, next) => {
    try {
      const now = new Date();
      // 1. Transition Scheduled -> Live when startTime is reached
      await Quiz.updateMany(
        { status: 'Scheduled', startTime: { $lte: now } },
        { $set: { status: 'Live' } }
      );
      // 2. Transition Live -> Completed when endTime is reached
      await Quiz.updateMany(
        { status: 'Live', endTime: { $lt: now } },
        { $set: { status: 'Completed' } }
      );
      next();
    } catch (err) {
      next(err);
    }
  });

  // API routes
  app.use('/api/auth', authRoutes);
  app.use('/api/admin', adminRoutes);
  app.use('/api/instructor', instructorRoutes);
  app.use('/api/candidate', candidateRoutes);

  // Global error handler — must be LAST
  app.use(errorHandler);


  return app;
};
