// filename: server/src/app.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import express, { Application } from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import swaggerUi from 'swagger-ui-express';
import { swaggerSpec } from './config/swagger';
import { env } from './config/env';
import authRoutes from './modules/auth/auth.routes';
import { errorHandler } from './middleware/errorHandler';

export const createApp = (): Application => {
  const app: Application = express();

  app.use(cors({ origin: env.CLIENT_URL, credentials: true }));
  app.use(express.json());
  app.use(cookieParser());

  // Swagger UI — interactive docs
  app.use(
    '/api-docs',
    swaggerUi.serve,
    swaggerUi.setup(swaggerSpec, {
      customSiteTitle: 'Quiz API Docs',
      swaggerOptions: { persistAuthorization: true },
    })
  );

  // Raw JSON spec (useful for Postman import, codegen, etc.)
  app.get('/api-docs.json', (_req, res) => {
    res.setHeader('Content-Type', 'application/json');
    res.send(swaggerSpec);
  });

  /**
   * @swagger
   * /health:
   *   get:
   *     tags: [Health]
   *     summary: Health check
   *     responses:
   *       200:
   *         description: Server is up
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 status: { type: string, example: ok }
   */
  app.get('/health', (_req, res) => res.json({ status: 'ok' }));

  // Convenience: redirect root → docs
  app.get('/', (_req, res) => res.redirect('/api-docs'));

  // API routes
  app.use('/api/auth', authRoutes);

  // Global error handler — must be LAST
  app.use(errorHandler);

  return app;
};
