// filename: errorHandler.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { ErrorRequestHandler } from 'express';
import { ApiError } from '../utils/ApiError';

export const errorHandler: ErrorRequestHandler = (err, req, res, _next) => {
  if (err instanceof ApiError) {
    res.status(err.status).json(err.toJSON());
    return;
  }
  // Last-resort log; swap console for pino/winston when wired
  console.error('[unhandled]', { path: req.path, err });
  res.status(500).json({ error: { code: 'INTERNAL_ERROR', message: 'Something went wrong' } });
};
