// filename: requireAuth.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { Request, Response, NextFunction } from 'express';
import { verifyToken } from '../utils/jwt';
import { COOKIE_NAME } from '../utils/cookie';
import { ApiError } from '../utils/ApiError';

export function requireAuth(req: Request, _res: Response, next: NextFunction): void {
  const cookies = req.cookies as Record<string, string | undefined> | undefined;
  const token = cookies?.[COOKIE_NAME];
  if (!token) {
    return next(new ApiError(401, 'NOT_AUTHENTICATED', 'Authentication required'));
  }
  try {
    const payload = verifyToken(token);
    req.user = { id: payload.sub, role: payload.role };
    next();
  } catch (err) {
    next(err);
  }
}
