// filename: validate.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { Request, Response, NextFunction, RequestHandler } from 'express';
import type { ZodTypeAny, z } from 'zod';
import { ApiError } from '../utils/ApiError';

type Source = 'body' | 'query' | 'params';

export const validate =
  <S extends ZodTypeAny>(schema: S, source: Source = 'body'): RequestHandler =>
  (req: Request, _res: Response, next: NextFunction): void => {
    const result = schema.safeParse(req[source]);
    if (!result.success) {
      const issues = result.error.issues.map((i) => ({
        path: i.path.join('.'),
        message: i.message,
      }));
      return next(new ApiError(400, 'VALIDATION_ERROR', 'Invalid request payload', { issues }));
    }
    // Replace with parsed/transformed data so downstream handlers get typed values
    (req[source] as z.infer<S>) = result.data;
    next();
  };
