// filename: src/main.jsx
// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles/main.scss';   // ← single global entry

ReactDOM.createRoot(document.getElementById('root')).render(<App />);
